tasks:
    - name: install nginx
      ansible.builtin.package:
        name: nginx
        state: present

    - name: start nginx
      ansible.builtin.service:
        name: nginx
        state: started 
        enabled: yes

    - name: remove the default content
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: absent

    - name: create html directory
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: directory 

    - name: download backend code
      ansible.builtin.get_url: 
        url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
        dest: /tmp/frontend.zip

    - name: Extract the zip file
      ansible.builtin.unarchive:
        src: /tmp/backend.zip
        dest: /usr/share/nginx/html
        remote_src: yes      

    - name: copy expense conf 
      ansible.builtin.templates: 
       src: expense.conf
       dest: /etc/nginx/default.d/expense.conf  

    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted   